### ISSUE TITLE
cant add time to datetime

### ISSUE THREAD

**Issue by ilyinss** [benyamindsmith/starBliss#13]
Hello, its me again!

in method you wrote:
`dt_tm <- lubridate::as_datetime(paste(dt, " 22:00:00"), tz = "UTC")`
then, user cant add a time. You are hardcoding it ((
can you edit it like this:
if user not add time - you paste 22:00
if user add time - you calculate strar map with his time

Sergey

**Comment by benyamindsmith** [comment]
This package aims to replicate the product produced by [MapsForMoments](https://mapsformoments.co.uk/9-star-map?step=design). @dieghernan  was kind enough to do alot of work for figuring out how to replicate the maps as far as datetime is concerned and learned that this is what MapsForMoments does. 

For more reading see Diego's blog in #7 and #10

**Comment by ilyinss** [comment]
yes, i'm understand it. but MapsForMoments - its commercial service.
i think your library can be more strong than MFM service because it's opensource

**Comment by benyamindsmith** [comment]
@ilyinss Going to close this issue. 

I hope you are enjoying the package still!
