### ISSUE TITLE
Set default linen_text parameters to have a nice format

### ISSUE THREAD

**Issue by laresbernardo** [benyamindsmith/starBliss#2]
Really nice package. I have an enhancement suggestion: why don't you set the default values for line1_text, line2_text, and line3_text parameters like so:
```
  line1_text = location,
  line2_text = format(date, "%B %d, %Y"),
  line3_text= [not sure how to get this one but use default]"
```

**Comment by benyamindsmith** [comment]
[Done](https://github.com/benyamindsmith/starBliss/commit/424c8c4d0faa4066a17a5396cc1c961929aafceb). 

Let me know if there are any other problems with this, otherwise I will close this issue.

**Comment by laresbernardo** [comment]
- Got `Error in format.default(date, "%B %d, %Y") : invalid 'trim' argument` error. This happens if you don't force `as.Date(date, origin = "1970-01-01")` when input is a string instead of a date.
- Did you consider enabling default coordinates for `line3_text`?

**Comment by benyamindsmith** [comment]
@laresbernardo could you show me the code you wrote which gave you the error?

**Comment by laresbernardo** [comment]
I simply passed a character value (`date = "1991-03-27"`) instead of `as.Date("1991-03-27")`

**Comment by benyamindsmith** [comment]
@laresbernardo I see. 

[This](https://github.com/benyamindsmith/starBliss/commit/a08a28a660f7a2eb43428ff27668c7bc2aa329ae) is the fix that I have.  This essentially runs `as.Date(date)` in the function to deal with varying formats. 

Initially I wrote the code to only handle YMD formats. 

Let me know how it works out on your end.

**Comment by laresbernardo** [comment]
Yes, `"1991-03-27"` is YMD format, but if it's simply set as a character value then it crashed. It seems to be fixed! Thanks

**Comment by laresbernardo** [comment]
Woops, closed but the coordinates default is not set yet (if you agree on setting it up of course)

**Comment by benyamindsmith** [comment]
@laresbernardo my bad! I wonder how its possible to do this. I'll look into it. If you find anything let me know!

**Comment by benyamindsmith** [comment]
@laresbernardo check out [this fix](https://github.com/benyamindsmith/starBliss/commit/cd37c60aba081283c517d96f350bd77c423b26ac). 

The geocoder is set by default to ArcGIS so the default geocoordinates are slightly different from what you'll find if you look it up on Google. 

```r
 plot_starmap(location= "Caracas, Venezuala")
```

![image](https://user-images.githubusercontent.com/46410142/214431786-05e85353-f0dc-480c-9656-a1d89ebbcfa8.png)

Let me know what you think!

**Comment by laresbernardo** [comment]
Good one, thanks! Really improved the UX here :)
