### ISSUE TITLE
Avoid changing users global options

### ISSUE THREAD

**Issue by laresbernardo** [benyamindsmith/starBliss#3]
Function "options" is undesirable in packages. Use `withr::with_options()` for a temporary change instead or suppress.
Ref: https://github.com/benyamindsmith/starBliss/blob/79a812f455cd6e4faf3cd8a74196c2676d876439/R/past_starmap.R#L54

**Comment by benyamindsmith** [comment]
@laresbernardo Noted. Is there a way to do this without having the code contained in its entirety of  `with_options()`?

**Comment by laresbernardo** [comment]
Not really. I think you could suggest in the demo or examples for users to change any option manually. You could also wrap the warning you want to suppress with `suppressWarnings()` I guess.

**Comment by benyamindsmith** [comment]
@laresbernardo see the fix I have [here](https://github.com/benyamindsmith/starBliss/commit/4f5c22166379d9c8ef28977c43255143d411f8df) let me know how it goes on your end.
