### ISSUE TITLE
Potential inconsistencies in results

### ISSUE THREAD

**Issue by laresbernardo** [benyamindsmith/starBliss#5]
I've tried to double check the results with mapsformoments output and it seems off (shouldn't they show the same?)

<img width="1159" alt="Screenshot 2023-01-20 at 8 11 04 AM" src="https://user-images.githubusercontent.com/25909073/213702840-1460f910-520b-4d87-92b2-be5b0f5b212e.png">

Also, not sure what to think about the line on the lower section. Do you have any documentation on how to interpret these?

**Comment by benyamindsmith** [comment]
@laresbernardo Just applied a fix to deal with longitude argument and it looks better: 
```r
plot_starmap(location="Caracas, Capital District,Venezuela",
             date="1992-02-29", 
             line1_text="Caracas, Capital District, Venezuela",
             line2_text= "February 29,1992") %>% 
    ggsave("ErrorPlot.png", plot = ., width = unit(10, 'in'), 
           height = unit(15, 'in'))
```
![image](https://user-images.githubusercontent.com/46410142/213895516-6871856d-6991-453e-aad0-39dbacf6fdab.png)


I looks like that there's an issue with the constellation lines joining in the proper order that MapsForMoments has. Thats why it still looks like that there are some inconsistencies.

**Comment by benyamindsmith** [comment]
@laresbernardo it also looks like there may be some projection issues as far as the map map is concerned.

**Comment by laresbernardo** [comment]
Using latest dev version, here's another reproducible example with 2 weird lines:
```
plot_starmap(
  location= "Caracas, Venezuela",
  date = as.Date("1991-03-17"),
  style = "black")
```

<img width="715" alt="Screenshot 2023-01-21 at 10 18 16 PM" src="https://user-images.githubusercontent.com/25909073/213899016-92acc2bd-928a-4a2a-9cf2-b8c3fe648285.png">

**Comment by benyamindsmith** [comment]
@laresbernardo  yes this is definitely a problem . I reason its related to the problem Kim Fitter encountered when she was trying to plot the constellation maps. See here: https://kimnewzealand.github.io/2019/02/21/celestial-maps/ 

I think I need to convert the constellation linestrings to points, crop the "over reaching points" and re-convert it back to a linestrings for them to work. 

I've been looking at `st_crop()` but it hasn't been working for our use case. 

__UPDATE:__ After looking into the issue I decided to bring the issue to StackOverflow for help ([link](https://stackoverflow.com/questions/75205747/how-to-remove-random-diagonal-lines-in-produced-by-geom-sf)).

**Comment by benyamindsmith** [comment]
@laresbernardo Check out the fix [here](https://github.com/benyamindsmith/starBliss/commit/0a8f359f194dff0c3fdb3c6c25478399b47dfe5e)- its based on the [StackOverflow answer](https://stackoverflow.com/questions/75205747/how-to-remove-random-diagonal-lines-from-star-map-vizualizations-produced-by-geo/75212722#75212722) I got . 

Let me know if there are still problems. Otherwise I will close this issue.

**Comment by laresbernardo** [comment]
Yeah, I think that did the trick! Love SO :)
